---
- name: Copy war
  hosts: Tomcat
  become: true

  tasks:
  - name: copy war to the tomcat server
    copy:
      src: /var/lib/jenkins/workspace/Git_Gitlab_Jenkins_Ansible_Tomcat/webapp/target/webapp.war
      dest: /opt/tomcat/latest/webapps
